解答の作成
Arisaarisa/05_index pull request #1
Opened 2020-01-23 16:40 UTC by Arisaarisa

これで完成して大丈夫ですか？？

2020-01-24 03:48 UTC, kazu-taka requested changes
@Arisaarisa 
確認お願いします！！

2020-01-24 03:48 UTC, kazu-taka commented on index.php
> +$incomplete_plans = $stmt->fetchAll(PDO::FETCH_ASSOC);
@Arisaarisa 
細かいですけど、ここの下に1行空行追加して下さい✨

2020-01-24 03:48 UTC, kazu-taka commented on index.php
> +$complete_plans = $stmt->fetchAll(PDO::FETCH_ASSOC);
@Arisaarisa 
ここの下にも空行追加で✨

2020-01-24 03:48 UTC, kazu-taka commented on index.php
> +            <?php echo h($errors['due_date']); ?>
@Arisaarisa 
この内容だと、完了済みのデータをぐるぐる回しているのに、$planは何も使用してないですよね！？
$errorsが連想配列になっているので、その連想配列を回してechoするのがシンプルです！
```php
<ul>
  <?php foreach ($errors as $key => $value) : ?>
    <?php echo h($value); ?>
  <?php endforeach; ?>
</ul>
```

2020-01-24 03:48 UTC, kazu-taka commented on index.php
> +        <?php break; ?>
@Arisaarisa 
このbreakは何用ですかね！？
削除しちゃってOKです！

2020-01-24 03:48 UTC, kazu-taka commented on index.php
> +        <?php else : ?>
@Arisaarisa 
elseとendifのインデントはifに合わせて下さい！

2020-01-24 03:48 UTC, kazu-taka commented on index.php
> +        <?php echo h($plan['title'] . date('Y/m/d', strtotime($plan['due_date']))); ?>
@Arisaarisa 
ここはstrtotimeを使用しないとうまく変換できない感じですかね！？

2020-01-24 03:59 UTC, Arisaarisa commented on index.php
> +        <?php echo h($plan['title'] . date('Y/m/d', strtotime($plan['due_date']))); ?>
strtotime使わないと全部1970/01/01になります！

2020-01-24 05:29 UTC, kazu-taka requested changes
@Arisaarisa 
追加で修正お願いします！

2020-01-24 05:29 UTC, kazu-taka commented on edit.php
> +        <?php foreach ($complete_plans as $plan) : ?>
@Arisaarisa 
editもindex.phpと同じように修正お願いします！

2020-01-24 05:29 UTC, kazu-taka commented on edit.php
> +        <?php foreach ($complete_plans as $plan) : ?>
ちなみに、spanタグを削除して、以下のように修正お願いします！
色が赤くならない時は教えて下さい！
index.phpも同じように修正お願いします！
```php
<?php if (count($errors) > 0) ; ?>
  <ul style="color:red;">
    <?php foreach ($errors as $key => $value) : ?>
      <li><?php echo h($value); ?></li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
```

2020-01-24 05:29 UTC, kazu-taka commented on index.php
> +      <?php if (date('Y-m-d') > $plan['due_date']) : ?>
@Arisaarisa 
ここはイコールつけたいって話していたと思うので、つけちゃってOKです！

2020-01-25 05:29 UTC, kazu-taka commented on index.php
> +    <?php foreach ($complete_plans as $plan) : ?>
@Arisaarisa 
ここincomplete_plansです！！

2020-02-03 02:21 UTC, merged